<a href="https://colab.research.google.com/github/shiv9956/AIML-summer-internship-2026/blob/main/election_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from textblob import TextBlob as tb
import plotly.graph_objects as go
import plotly.express as xp

In [4]:
modi = pd.read_csv("/content/modi_reviews.csv")
rahul = pd.read_csv("/content/rahul_reviews.csv")

In [5]:
modi.head()

   Unnamed: 0  ...                                              Tweet
0           0  ...  @anjanaomkashyap I am seeing you as future #bj...
1           1  ...  #LokSabhaElections2019 \n23rd May 2019 will re...
2           2  ...  #LokSabhaElections2019 \n23rd May 2019 will re...
3           3  ...  PM Modi creates a new record of being the only...
4           4  ...  @abhijitmajumder Appointment of Successor! \n\...

[5 rows x 3 columns]

In [6]:
modi.shape

(25688, 3)

In [7]:
rahul.head()

   Unnamed: 0  ...                                              Tweet
0           0  ...  Wonder why no academic or journalist asks INC ...
1           1  ...  Congrats for the change #australiavotes2019 an...
2           2  ...  Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...
3           3  ...  @ajaymaken @RahulGandhi And as a final touch, ...
4           4  ...  #LokSabhaElections2019 Anyone not having mass ...

[5 rows x 3 columns]

In [8]:
rahul.shape

(14261, 3)

In [9]:
tb(modi["Tweet"][10]).sentiment
"""*   **Polarity**: This value indicates the emotional charge of the text,
ranging from -1 (very negative) to +1 (very positive).
A polarity of 0.0 suggests a neutral sentiment.

*   **Subjectivity**: This value indicates how subjective or objective the text is,
 ranging from 0.0 (very objective) to 1.0 (very subjective). Objective text expresses facts,
 while subjective text expresses opinions, feelings, or beliefs.
"""

Sentiment(polarity=0.0, subjectivity=0.0)

In [11]:
tb(rahul["Tweet"][2]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [12]:
modi["Tweet"] = modi["Tweet"].astype(str)
rahul["Tweet"] = rahul["Tweet"].astype(str)

def find_polarity(review):
  return tb(review).sentiment.polarity

In [14]:
modi["Polarity"] = modi["Tweet"].apply(find_polarity)
rahul["Polarity"] = rahul["Tweet"].apply(find_polarity)

In [16]:
modi

       Unnamed: 0  ...  Polarity
0               0  ...  0.350000
1               1  ...  0.800000
2               2  ...  0.800000
3               3  ...  0.312121
4               4  ...  0.098788
...           ...  ...       ...
25683       25683  ...  0.000000
25684       25684  ...  0.209524
25685       25685  ... -0.700000
25686       25686  ...  0.000000
25687       25687  ... -0.213542

[25688 rows x 4 columns]

In [17]:
rahul

       Unnamed: 0  ...  Polarity
0               0  ...  0.218750
1               1  ...  0.000000
2               2  ...  0.000000
3               3  ...  0.320000
4               4  ... -0.166667
...           ...  ...       ...
14256       14256  ...  0.000000
14257       14257  ... -0.500000
14258       14258  ...  0.080000
14259       14259  ...  0.080000
14260       14260  ...  0.080000

[14261 rows x 4 columns]

In [18]:
modi["Label"] = np.where(modi["Polarity"] > 0,"Positive","Negative")
modi["Label"][modi["Polarity"] == 0] = "Neutral"

rahul["Label"] = np.where(rahul["Polarity"] > 0,"Positive","Negative")
rahul["Label"][rahul["Polarity"] == 0] = "Neutral"

/tmp/ipykernel_5564/1821850646.py:2: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


/tmp/ipykernel_5564/1821850646.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_5564/1821850646.py:5: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


/tmp/ipykernel_5564/1821850646.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy