<a href="https://colab.research.google.com/github/shiv9956/AIML-summer-internship-2026/blob/main/pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\Users\shivd\Downloads\zomato.csv") # Read the CSV file into a pandas DataFrame
df.head(2) # Display the first 2 rows of the DataFrame

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari

In [ ]:
df.drop(["url","address","phone","reviews_list"],axis=1,inplace=True) # Drop specified columns from the DataFrame
df.head(2) # Display the first 2 rows of the modified DataFrame

In [ ]:
df.drop(["url","address","phone","reviews_list"],axis=1,inplace=True)
df.head(2)

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),menu_item,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,[],Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,[],Buffet,Banashankari

In [ ]:
df.columns # Display the column names of the DataFrame

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)',
       'menu_item', 'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [ ]:
df.drop_duplicates(inplace=True) # Remove duplicate rows from the DataFrame
df.shape # Display the shape (number of rows and columns) of the DataFrame

(51630, 13)

In [ ]:
df["rate"].unique() # Display unique values in the 'rate' column

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '3.6/5',  '4.6/5',  '4.0/5',  '4.2/5',
  '3.9/5',  '3.1/5',  '3.0/5',  '3.2/5',  '3.3/5',  '2.8/5',  '4.4/5',
  '4.3/5',    'NEW',  '2.9/5',  '3.5/5',      nan,  '2.6/5', '3.8 /5',
  '3.4/5',  '4.5/5',  '2.5/5',  '2.7/5',  '4.7/5',  '2.4/5',  '2.2/5',
  '2.3/5', '3.4 /5',      '-', '3.6 /5',  '4.8/5', '3.9 /5', '4.2 /5',
 '4.0 /5', '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
 '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5', '4.3 /5',
 '4.4 /5',  '4.9/5',  '2.1/5',  '2.0/5',  '1.8/5', '4.6 /5', '4.9 /5',
 '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5',
 '2.0 /5', '1.8 /5']
Length: 65, dtype: str

In [ ]:
#removing "NEW","-" and "/5" from rate column
def handlerate(value) :
    if (value=="NEW" or value=="-"):
        return np.nan # Replace 'NEW' or '-' with NaN (Not a Number)
    else:
        value =str(value).split('/')
        value = value[0]
        return float(value)

df["rate"]= df["rate"].apply(handlerate) # Apply the handlerate function to the 'rate' column
df["rate"].head() # Display the first 5 processed values of the 'rate' column

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64

In [ ]:
df["rate"].unique() # Display unique values in the 'rate' column after cleaning

array([4.1, 3.8, 3.7, 3.6, 4.6, 4. , 4.2, 3.9, 3.1, 3. , 3.2, 3.3, 2.8,
       4.4, 4.3, nan, 2.9, 3.5, 2.6, 3.4, 4.5, 2.5, 2.7, 4.7, 2.4, 2.2,
       2.3, 4.8, 4.9, 2.1, 2. , 1.8])

In [ ]:
df.fillna({"rate": df["rate"].mean()}, inplace=True) # Fill NaN values in 'rate' column with its mean
df['rate'].isnull().sum() # Check for any remaining null values in the 'rate' column

np.int64(0)

In [ ]:
df.info() # Display a concise summary of the DataFrame

<class 'pandas.DataFrame'>
Index: 51630 entries, 0 to 51716
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51630 non-null  str
 1   online_order                 51630 non-null  str
 2   book_table                   51630 non-null  str
 3   rate                         51630 non-null  float64
 4   votes                        51630 non-null  int64
 5   location                     51609 non-null  str
 6   rest_type                    51403 non-null  str
 7   dish_liked                   23604 non-null  str
 8   cuisines                     51585 non-null  str
 9   approx_cost(for two people)  51286 non-null  str
 10  menu_item                    51630 non-null  str
 11  listed_in(type)              51630 non-null  str
 12  listed_in(city)              51630 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 5.5 MB

In [ ]:
df.dropna(inplace=True) # Drop rows with any NaN values from the DataFrame
df.head(2) # Display the first 2 rows of the DataFrame after dropping NaN values

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),menu_item,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,[],Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,[],Buffet,Banashankari

In [ ]:
df.shape # Display the shape (number of rows and columns) of the DataFrame

(23402, 13)

In [ ]:
df.rename(columns={"approx_cost(for two people)":"Cost2plates","listed_in(type)":"Type"},inplace=True) # Rename columns for better readability
df.head(2) # Display the first 2 rows of the DataFrame with renamed columns

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,Cost2plates,menu_item,Type,listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,[],Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,[],Buffet,Banashankari

In [ ]:
df["location"].unique() # Display unique values in the 'location' column

<StringArray>
[                 'Banashankari',                  'Basavanagudi',
                     'Jayanagar',            'Kumaraswamy Layout',
          'Rajarajeshwari Nagar',                   'Mysore Road',
                   'Uttarahalli',               'South Bangalore',
                   'Vijay Nagar',             'Bannerghatta Road',
                      'JP Nagar',                           'BTM',
                 'Wilson Garden',         'Koramangala 5th Block',
                  'Shanti Nagar',                 'Richmond Road',
                   'City Market',                     'Bellandur',
                 'Sarjapur Road',                  'Marathahalli',
                           'HSR',              'Old Airport Road',
                   'Indiranagar',         'Koramangala 1st Block',
                'East Bangalore',                       'MG Road',
                  'Brigade Road',                  'Lavelle Road',
                 'Church Street',                        'Ulsoor',
                'Residency Road',                  'Shivajinagar',
                 'Infantry Road',                'St. Marks Road',
               'Cunningham Road',              'Race Course Road',
                        'Domlur',         'Koramangala 8th Block',
                   'Frazer Town',                       'Ejipura',
                 'Vasanth Nagar',            'Jeevan Bhima Nagar',
               'Old Madras Road',             'Commercial Street',
         'Koramangala 6th Block',                      'Majestic',
                 'Langford Town',         'Koramangala 7th Block',
                   'Brookefield',                    'Whitefield',
    'ITPL Main Road, Whitefield', 'Varthur Main Road, Whitefield',
         'Koramangala 2nd Block',         'Koramangala 3rd Block',
         'Koramangala 4th Block',                   'Koramangala',
                  'Bommanahalli',                    'Hosur Road',
                 'Seshadripuram',               'Electronic City',
                     'Banaswadi',               'North Bangalore',
                      'RT Nagar',                  'Kammanahalli',
                        'Hennur',                    'HBR Layout',
                  'Kalyan Nagar',                  'Thippasandra',
                'CV Raman Nagar',                 'Kaggadasapura',
               'Kanakapura Road',                      'Nagawara',
               'Rammurthy Nagar',                   'Sankey Road',
             'Central Bangalore',                  'Malleshwaram',
                'Sadashiv Nagar',            'Basaveshwara Nagar',
                   'Rajajinagar',                  'New BEL Road',
                'West Bangalore',                   'Yeshwantpur',
                  'Sanjay Nagar',                'Sahakara Nagar',
                     'Jalahalli',                     'Yelahanka',
                   'Magadi Road',                      'KR Puram']
Length: 88, dtype: str

In [ ]:
df["Cost2plates"].unique() # Display unique values in the 'Cost2plates' column

<StringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '750',   '200',   '850', '1,200',   '150',   '350',   '250',
 '1,500', '1,300', '1,000',   '100',   '900', '1,100', '1,600',   '950',
   '230', '1,700', '1,400', '1,350', '2,200', '2,000', '1,800', '1,900',
   '180',   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40',
 '1,250', '3,500', '4,000', '2,400', '1,450', '3,200', '6,000', '1,050',
 '4,100', '2,300',   '120', '2,600', '5,000', '3,700', '1,650', '2,700',
 '4,500']
Length: 57, dtype: str

In [ ]:
#remove comma from cost2plates
def handlecomma(value):
    value=str(value)
    if ',' in value :
        value=value.replace(',','')
        return float(value)
    else:
        return float(value)
df['Cost2plates']= df['Cost2plates'].apply(handlecomma) # Apply the handlecomma function to clean 'Cost2plates' column
df['Cost2plates'].unique() # Display unique values in the 'Cost2plates' column after cleaning

array([ 800.,  300.,  600.,  700.,  550.,  500.,  450.,  650.,  400.,
        750.,  200.,  850., 1200.,  150.,  350.,  250., 1500., 1300.,
       1000.,  100.,  900., 1100., 1600.,  950.,  230., 1700., 1400.,
       1350., 2200., 2000., 1800., 1900.,  180.,  330., 2500., 2100.,
       3000., 2800., 3400.,   40., 1250., 3500., 4000., 2400., 1450.,
       3200., 6000., 1050., 4100., 2300.,  120., 2600., 5000., 3700.,
       1650., 2700., 4500.])

In [ ]:
df.head() # Display the first 5 rows of the DataFrame

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,Cost2plates,menu_item,Type,listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,[],Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,[],Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,[],Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,[],Buffet,Banashankari

In [ ]:
rest_types = df['rest_type'].value_counts(ascending=False) # Calculate value counts for 'rest_type' column
rest_types

rest_type
Casual Dining                7388
Quick Bites                  5268
Cafe                         2381
Dessert Parlor               1085
Casual Dining, Bar            987
                             ...
Bar, Pub                        5
Club, Casual Dining             4
Dessert Parlor, Kiosk           2
Dhaba                           1
Food Court, Casual Dining       1
Name: count, Length: 73, dtype: int64

In [ ]:
rest_type_lessthan1000 = rest_types[rest_types < 1000] # Filter rest types with counts less than 1000
rest_type_lessthan1000

rest_type
Casual Dining, Bar           987
Delivery                     707
Bar                          358
Bar, Casual Dining           348
Takeaway, Delivery           343
                            ...
Bar, Pub                       5
Club, Casual Dining            4
Dessert Parlor, Kiosk          2
Dhaba                          1
Food Court, Casual Dining      1
Name: count, Length: 69, dtype: int64

In [ ]:
# if data less than 1000 in rest type, sum them all and count as others
def handle_rest_type(value):
    if value in rest_type_lessthan1000:
        return 'others'
    else:
        return value

df['rest_type'] = df['rest_type'].apply(handle_rest_type) # Apply the function to group less frequent rest types

df['rest_type'].value_counts() # Display value counts of 'rest_type' after handling

rest_type
Casual Dining     7388
others            7280
Quick Bites       5268
Cafe              2381
Dessert Parlor    1085
Name: count, dtype: int64

In [ ]:
#cleaning cuisines
cuisines= df['cuisines'].value_counts(ascending=False) # Calculate value counts for 'cuisines' column

cuisines_lessthan100= cuisines[cuisines < 100] # Filter cuisines with counts less than 100

def handle_cuisines(value):
    if value in cuisines_lessthan100:
        return 'others'
    else:
        return value

df['cuisines'] = df['cuisines'].apply(handle_cuisines) # Apply the function to group less frequent cuisines

df['cuisines'].value_counts() # Display value counts of 'cuisines' after handling

cuisines
others                                              17668
North Indian                                         1160
North Indian, Chinese                                 778
South Indian                                          367
Cafe                                                  285
South Indian, North Indian, Chinese                   233
Bakery, Desserts                                      217
Desserts, Beverages                                   216
Ice Cream, Desserts                                   212
Chinese                                               210
Desserts                                              209
Biryani                                               169
Chinese, Momos                                        162
Finger Food                                           151
Fast Food                                             150
North Indian, Chinese, Biryani                        139
Mithai, Street Food                                   138
North Indian, Mughlai                                 134
Burger, Fast Food                                     132
Cafe, Continental                                     124
Desserts, Ice Cream                                   122
Chinese, Thai                                         117
Pizza, Fast Food                                      106
South Indian, North Indian, Chinese, Street Food      103
Cafe, Desserts                                        100
Name: count, dtype: int64